Add SpectralOps and Teller
TaptuIT/awesome-devsecops pull request #40
Opened 2021-05-27 08:02 UTC by jondot

2021-05-28 02:08 UTC, iamscottcab requested changes

2021-05-28 02:08 UTC, iamscottcab commented on readme.md
> +- [Teller](https://github.com/spectralops/teller) - _Spectral_ A secrets management tool for developers - never leave your command line for secrets.
This is just missing a `-` between the name and description.

2021-05-28 02:11 UTC, iamscottcab requested changes
Just need to resolve the comment about the typo on line 205.

2021-05-28 08:18 UTC, jondot commented
Thanks, fixed

2021-05-31 04:46 UTC, iamscottcab approved these changes

2021-05-31 04:46 UTC, merged