Add Supply Chain Security category + Preflight under supply chain
TaptuIT/awesome-devsecops pull request #42
Opened 2021-05-27 08:09 UTC by jondot

2021-05-28 02:10 UTC, iamscottcab requested changes

2021-05-28 02:10 UTC, iamscottcab commented on readme.md
> +### Supply Chain Security
Not sure if @JakobTheDev will want this one moved, but the sections seem alphabetized so my assumption is that this should go under `Static Analysis`?

2021-05-28 08:20 UTC, jondot commented
Thanks, fixed

2021-05-31 04:46 UTC, iamscottcab approved these changes

2021-05-31 04:47 UTC, merged